<a href="https://colab.research.google.com/github/25041097-jesus/Probabilidad/blob/main/Unidad1/Practica%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Probabilidad y estadistica**

Unidad 1

Practica 5:

Docente: Dr. Jose Gabriel Rodriguez Rivas

Alumno: Joan Jesus Varela Cervantes

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

In [28]:
covid=pd.read_csv("/20-06-30-COVID19MEXICO - codificado.csv",encoding="ISO-8859-1")

#/20-06-30-COVID19MEXICO - codificado.csv

In [29]:
covid.head()

,ï»¿ORIGEN,SECTOR,SEXO,ENTIDAD_NAC,TIPO_PACIENTE,FECHA_INGRESO,FECHA_SINTOMAS,FECHA_DEF,INTUBADO,NEUMONIA,...,EPOC,ASMA,INMUSUPR,HIPERTENSION,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,RESULTADO,UCI
0,1,4,Hombre,Zacatecas,Hospitalizado,27/03/2020,27/03/2020,9999-99-99,No,No,...,No,No,No,No,No,No,No,No,Negativo,No
1,1,12,Hombre,Zacatecas,Hospitalizado,06/04/2020,02/04/2020,9999-99-99,No,Si,...,No,No,No,No,No,No,No,No,Negativo,No
2,1,12,Mujer,Zacatecas,Hospitalizado,15/04/2020,12/04/2020,9999-99-99,No,Si,...,No,No,Si,No,No,No,No,No,Negativo,No
3,2,12,Mujer,Zacatecas,Hospitalizado,08/05/2020,08/05/2020,9999-99-99,Si,No,...,No,No,No,No,No,No,No,No,Negativo,Si
4,2,12,Mujer,Zacatecas,Hospitalizado,08/05/2020,08/05/2020,9999-99-99,Si,No,...,No,No,No,No,No,No,No,No,Negativo,Si

In [30]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496445 entries, 0 to 496444
Data columns (total 23 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ï»¿ORIGEN       496445 non-null  int64
 1   SECTOR          496445 non-null  int64
 2   SEXO            496445 non-null  object
 3   ENTIDAD_NAC     496445 non-null  object
 4   TIPO_PACIENTE   496445 non-null  object
 5   FECHA_INGRESO   496445 non-null  object
 6   FECHA_SINTOMAS  496445 non-null  object
 7   FECHA_DEF       496445 non-null  object
 8   INTUBADO        496445 non-null  object
 9   NEUMONIA        496445 non-null  object
 10  EDAD            496445 non-null  int64
 11  EMBARAZO        496445 non-null  object
 12  DIABETES        496445 non-null  object
 13  EPOC            496445 non-null  object
 14  ASMA            496445 non-null  object
 15  INMUSUPR        496445 non-null  object
 16  HIPERTENSION    496445 non-null  object
 17  CARDIOVASCULAR  496445 non-null  object
 18  OBESIDAD        496445 non-null  object
 19  RENAL_CRONICA   496445 non-null  object
 20  TABAQUISMO      496445 non-null  object
 21  RESULTADO       496445 non-null  object
 22  UCI             496445 non-null  object
dtypes: int64(3), object(20)
memory usage: 87.1+ MB

In [31]:
covid.EDAD.max()

120

In [32]:
covid.EDAD.min()

0

In [33]:
covid.EDAD.describe()

count    496445.000000
mean         42.849033
std          16.774223
min           0.000000
25%          31.000000
50%          41.000000
75%          54.000000
max         120.000000
Name: EDAD, dtype: float64

In [34]:
conteo_edades=['EDAD'].value_counts().sort_index()

plt.bar(conteo_edades.index,conteo_edades.values,color='skyblue',edegecolor='black',alpha=0.6)
plt.title('pruebas COVID por edad')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()

AttributeError: 'list' object has no attribute 'value_counts'

In [ ]:
media= covid.EDAD.mean()
rangos=[0,10,20,30,40,50,60,70,80,90,100,120]
plt.hist(covid.EDAD,bins=rangos,edgecolor='black')
plt.title("Histograma de pruebas COVID por grupos de Edad")
plt.axvline(media,color='y',linestyle='dashed',linewidth=2,label= f'Media Edad'{media:.2f}')
plt.legend
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()

In [ ]:
conteo_sexo=covid['SEXO'].value_counts()
plt.bar(conteo_sexo.index.astype(str),conteo_sexo.values,color='light blue',edgecolor='black',alpha=0.7)
plt.title('Pruebas COVID por sexo')
plt.xlabel('Sexo')
plt.ylabel('Frecuencia')
plt.show()

In [ ]:
conteo_tipo_paciente